import { Plugin } from '../types/plugin';
import { generateVstCode } from './codeGenerator';

function downloadFile(filename: string, content: string, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function generateCMakeLists(plugin: Plugin): string {
  const safeId = plugin.name.replace(/[^a-zA-Z0-9_]/g, '_');
  return `cmake_minimum_required(VERSION 3.22)
project(${safeId} VERSION ${plugin.metadata.version})

# Set the JUCE path — change this to your local JUCE installation
set(JUCE_DIR "" CACHE PATH "Path to JUCE")
add_subdirectory(\${JUCE_DIR} JUCE)

juce_add_plugin(${safeId}
    COMPANY_NAME "${plugin.metadata.manufacturer}"
    PLUGIN_MANUFACTURER_CODE Vstc
    PLUGIN_CODE ${safeId.substring(0, 4).padEnd(4, 'A')}
    FORMATS VST3 AU Standalone
    PRODUCT_NAME "${plugin.name}"
    DESCRIPTION "${plugin.metadata.description}"
    IS_SYNTH ${plugin.type === 'instrument' ? 'TRUE' : 'FALSE'}
    NEEDS_MIDI_INPUT ${plugin.type === 'instrument' ? 'TRUE' : 'FALSE'}
    NEEDS_MIDI_OUTPUT FALSE
    EDITOR_WANTS_KEYBOARD_FOCUS FALSE
    VST3_CATEGORIES "${plugin.metadata.category}"
)

juce_generate_juce_header(${safeId})

target_sources(${safeId}
    PRIVATE
        src/${safeId}.h
        src/${safeId}.cpp
)

target_compile_definitions(${safeId}
    PUBLIC
        JUCE_WEB_BROWSER=0
        JUCE_USE_CURL=0
        JUCE_VST3_CAN_REPLACE_VST2=0
)

target_link_libraries(${safeId}
    PRIVATE
        juce::juce_audio_utils
    PUBLIC
        juce::juce_recommended_config_flags
        juce::juce_recommended_lto_flags
        juce::juce_recommended_warning_flags
)
`;
}

function generateReadme(plugin: Plugin): string {
  const safeId = plugin.name.replace(/[^a-zA-Z0-9_]/g, '_');
  return `# ${plugin.name}

${plugin.metadata.description}

**Manufacturer:** ${plugin.metadata.manufacturer}  
**Version:** ${plugin.metadata.version}  
**Category:** ${plugin.metadata.category}  
**Type:** ${plugin.type === 'effect' ? 'Audio Effect' : 'Instrument'}  
**Unique ID:** ${plugin.metadata.uniqueId}  

## Parameters

| Name | Min | Max | Default | Unit | Curve |
|------|-----|-----|---------|------|-------|
${plugin.parameters.map(p =>
  `| ${p.name} | ${p.min} | ${p.max} | ${p.defaultValue} | ${p.unit || '-'} | ${p.curve || 'linear'} |`
).join('\n')}

## Building

### Prerequisites
- [JUCE Framework](https://juce.com) 7.x
- CMake 3.22+
- C++17 compiler (Clang, GCC, or MSVC)

### Steps

\`\`\`bash
git clone https://github.com/your-org/${safeId}
cd ${safeId}
mkdir build && cd build
cmake .. -DJUCE_DIR=/path/to/JUCE
cmake --build . --config Release
\`\`\`

The built plugin will be in \`build/${safeId}_artefacts/Release/\`.

## Interface

- Canvas size: ${plugin.interface.width} × ${plugin.interface.height} px
- Widgets: ${plugin.interface.widgets.length}
${plugin.interface.widgets.map(w => `  - ${w.type.toUpperCase()}: ${w.label}`).join('\n')}

---
*Generated by [VST Plugin Creator](https://github.com/yourusername/vst-plugin-creator)*
`;
}

export async function exportPlugin(plugin: Plugin): Promise<void> {
  const { headerCode, sourceCode, factoryCode } = generateVstCode(plugin);
  const safeId = plugin.name.replace(/[^a-zA-Z0-9_]/g, '_');

  // Build the full JUCE-style plugin source
  const fullSource = `${sourceCode}

// ============================================================
// Factory Registration
// ============================================================
${factoryCode}
`;

  const manifest = {
    name: plugin.name,
    type: plugin.type,
    version: plugin.metadata.version,
    manufacturer: plugin.metadata.manufacturer,
    category: plugin.metadata.category,
    description: plugin.metadata.description,
    uniqueId: plugin.metadata.uniqueId,
    parameters: plugin.parameters.map((p) => ({
      id: p.id,
      name: p.name,
      type: p.type,
      category: p.category,
      min: p.min,
      max: p.max,
      defaultValue: p.defaultValue,
      unit: p.unit,
      curve: p.curve,
    })),
    interface: {
      width: plugin.interface.width,
      height: plugin.interface.height,
      backgroundColor: plugin.interface.backgroundColor,
      widgets: plugin.interface.widgets,
    },
    exportedAt: new Date().toISOString(),
  };

  // Download each file with a brief stagger to avoid browser blocking
  const files: [string, string, string][] = [
    [`${safeId}.h`, headerCode, 'text/plain'],
    [`${safeId}.cpp`, fullSource, 'text/plain'],
    [`CMakeLists.txt`, generateCMakeLists(plugin), 'text/plain'],
    [`README.md`, generateReadme(plugin), 'text/markdown'],
    [`${safeId}.plugin.json`, JSON.stringify(manifest, null, 2), 'application/json'],
  ];

  for (let i = 0; i < files.length; i++) {
    await new Promise<void>((resolve) => {
      setTimeout(() => {
        downloadFile(...files[i]);
        resolve();
      }, i * 200);
    });
  }
}
